remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: SBuntingCompiled's Portfolio
description: This is where I share not only my skills, but interests and projects I have been working on.

collections:
  pages:
    output: true
    permalink: /:name/